version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auto-park-system
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/pgdata:/var/lib/postgresql/data

  pgadmin: # http://localhost:5050/browser/
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mad.rijkaard@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5.1-debian-11-r58
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./volumes/kafka:/bitnami/kafka
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    volumes:
      - ./volumes/cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES;' 127.0.0.1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  init-cassandra:
    image: cassandra:4.1
    container_name: init_cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "
      echo '🔧 Criando keyspace auto_park_system (se necessário)...';
      cqlsh cassandra 9042 -e \"
      CREATE KEYSPACE IF NOT EXISTS auto_park_system
      WITH replication = {'class':'SimpleStrategy','replication_factor':1};
      \";
      echo '✅ Keyspace pronto.';"
    restart: "no"
