server:
  port: 3003

grpc:
  server:
    port: 9090

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auto-park-system
    username: admin
    password: admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: auto-park-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: auto_park_system

logging:
  level:
    org.springframework.r2dbc: DEBUG
